<?php

/**
 * @file
 *
 * @todo Support notifications from publishers over HTTP.
 */

/**
 * Implementation of hook_menu().
 */
function push_hub_menu() {
  $items = array();
  $items['pubsubhubbub/endpoint'] = array(
   'page callback' => 'push_hub_endpoint',
   'page arguments' => array(3, 4),
   'access callback' => 'user_access',
   'access arguments' => array('access content'), // @todo Specific permission
   'file' => 'push_hub.pages.inc',
   'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Instantiates a PuSH Hub object.
 */
function push_hub() {
  module_load_include('inc', 'push_hub', 'PuSHHub');
  return PuSHHub::instance();
}