<?php

// Time in seconds that a request is valid.
define('KEYAUTH_EXPIRY', 30);
// Hash algorithm to use.
define('KEYAUTH_ALGORITHM', 'sha1');

/**
 * Implementation of hook_cron().
 *
 * Clear old values from the nonce table.
 */
function keyauth_cron() {
  $expiry_time = time() - KEYAUTH_EXPIRY;
  db_query("DELETE FROM {keyauth_timestamp_nonce} WHERE timestamp < '%s'", $expiry_time);
}

/**
 * Implementation of hook_menu().
 */
function keyauth_menu() {
  $items = array();
  $items['admin/build/keys'] = array(
    'title'             => 'Authentication keys',
    'description'       => 'Manage authentication keys.',
    'page callback'     => 'keyauth_admin_keys_list',
    'access arguments'   => array('administer authentication keys'),
    'file'              => 'keyauth.admin.inc',
  );
  $items['admin/build/keys/%'] = array(
    'title'             => 'Edit key',
    'access arguments'   => array('administer authentication keys'),
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('keyauth_admin_keys_form', 3),
    'file'              => 'keyauth.admin.inc',
    'type'              => MENU_CALLBACK,
  );
  $items['admin/build/keys/%/delete'] = array(
    'access arguments'   => array('administer authentication keys'),
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('keyauth_admin_keys_delete_confirm', 3),
    'file'              => 'keyauth.admin.inc',
    'type'              => MENU_CALLBACK,
  );
  $items['admin/build/keys/%/generate'] = array(
    'access arguments'   => array('administer authentication keys'),
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('keyauth_admin_keys_generate_confirm', 3),
    'file'              => 'keyauth.admin.inc',
    'type'              => MENU_CALLBACK,
  );
  $items['admin/build/keys/list'] = array(
    'title'             => 'List',
    'type'              => MENU_DEFAULT_LOCAL_TASK,
    'access arguments'   => array('administer authentication keys'),
    'weight'            => -10,
  );
  $items['admin/build/keys/new'] = array(
    'title'             => 'New key',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('keyauth_admin_keys_form', 3),
    'access arguments'   => array('administer authentication keys'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'keyauth.admin.inc',
  );
  $items['admin/build/keys/add'] = array(
    'title'             => 'Add existing key',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('keyauth_admin_keys_form', 3),
    'access arguments'   => array('administer authentication keys'),
    'type'              => MENU_LOCAL_TASK,
    'file'              => 'keyauth.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function keyauth_perm() {
  return array('administer authentication keys');
}

/**
 * Include key auth functions.
 */
function keyauth_include() {
  module_load_include('inc', 'keyauth');
}

/**
 * Save a key set.
 *
 * @param $title
 *   Tite of key set. If empty, title will not be changed.
 * @param $public_key
 *   Public key. If empty, a new public key will generated. A key set is
 *   identified by its public key.
 * @param $private_key
 *   Private key, if omitted, a new private key will be generated.
 *
 * @return
 *   Complete key set as an array.
 */
function keyauth_admin_keys_save($title = '', $public_key = '', $private_key = '') {
  keyauth_include();
  $save = array(
    'public_key' => empty($public_key) ? keyauth_random('md5') : $public_key,
    'private_key' => empty($private_key) ? keyauth_random('sha1') : $private_key,
  );
  if (!empty($title)) {
    $save['title'] = $title;
  }
  drupal_write_record('keyauth_keys', $save, empty($public_key) ? NULL : $public_key);
  return $save;
}
