<?php
// $Id: views_rss.module,v 1.1 2009/09/22 16:49:55 rsoden Exp $ 

/**
 * Implementation of hook_views_api().
 */
function views_rss_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'views_rss') .'/views',
  );
}

/**
 * Implementation of hook_theme().
 */
function views_rss_theme() {
  $path = drupal_get_path('module', 'views_rss');
  return array(
    'views_rss_fields_item' => array(
      'arguments' => array('item' => array()),
      'file' => 'views_rss_views_fields.theme.inc',
      'template' => 'views-rss-fields-item',
      'path' => "$path/views",
    ),
   'views_rss_feed_icon' => array(
      'arguments' => array('url', 'title', 'icon'),
      'file' => 'views_rss_views_fields.theme.inc',
      'path' => "$path/views",
    ),
    'views_rss_feed_description' => array(
       'arguments' => array('description', 'view'),
       'file' => 'views_rss_views_fields.theme.inc',
       'path' => "$path/views",
     ),
  );
}
