<?php

include_once('activity_feeds.features.inc'); 

/**
 * Implementation of hook_feeds_plugins().
 */
function activity_feeds_feeds_plugins() {
  return array(
    'ActivityFeedsUserParser' => array(
      'name' => 'Activity Feeds Parser',
      'description' => 'Look up users by name.',
      'help' => 'Just like SimplePie parser with one difference: looks up users by RSS/Atom author name, look for User ID mapping source.',
      'handler' => array(
        'parent' => 'FeedsSimplePieParser',
        'class' => 'ActivityFeedsUserParser',
        'file' => 'ActivityFeedsUserParser.inc',
        'path' => drupal_get_path('module', 'activity_feeds'),
      ),
    ),
  );
}
