<?php
/**
 * @file
 * Synchronize local users from another Drupal site that exposes user
 * information with PuSH user module.
 *
 * @todo Add authentication with url_sign module.
 *
 * - Don't require a user to sign a URL.
 * - Add shared private key between OP and RPs.
 * - Extend FeedsPubSubFetcher in sync_user and sign every request URL with
 *   private key.
 * - Verify signature in push_user before returning the feed.
 * - Add nonce and random token to signed URL?
 */

include_once('sync_user.features.inc');

/**
 * Implementation of hook_menu().
 */
function sync_user_menu() {
  $items = array();
  $items['admin/user/sync'] = array(
    'title' => 'Synchronize users',
    'description' => 'Synchronize users from another Drupal site.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sync_user_form', 'administer users'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_feeds_plugins().
 */
function sync_user_feeds_plugins() {
  $info = array();
  $info['SyncUserParser'] = array(
    'name' => 'Sync User parser',
	    'description' => 'Parses user account information from feeds provided by the PuSH User module.',
	    'handler' => array(
	      'parent' => 'FeedsParser',
	      'class' => 'SyncUserParser',
	      'file' => 'SyncUserParser.inc',
	      'path' => drupal_get_path('module', 'sync_user'),
	    ),
	  );
	return $info;
}

/**
 * Implementation of hook_user().
 *
 * Subscribe/unsubscribe users when they register.
 */
function sync_user_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'insert':
      if (isset($edit['auth_openid'])) {
        sync_user_subscribe($account->uid, sync_user_subscription_url($edit['auth_openid']));
      }
      break;
    case 'delete':
      sync_user_unsubscribe($account->uid);
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function sync_user_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_profile_form' && user_access('administer users')) {
    $account = $form['_account']['#value'];
    if ($importer = feeds_importer('user_updates')) {
      // Build form.
      $source = feeds_source($importer->id, $account->uid);
      $form['sync_user_feed'] = array(
        '#type' => 'fieldset',
        '#title' => t('Synchronization feed'),
        '#description' => t('This URL is generated based on !sync_settings.', array('!sync_settings' => l(t('Synchronize users settings'), 'admin/user/sync'))),
      );
      $form['sync_user_feed']['resubscribe'] = array(
        '#value' => t('Subscribe'),
        '#type' => 'submit',
        '#submit' => array('sync_user_subscribe_submit'),
        '#weight' => 2,
      );
      if ($url = $source->config['KeyAuthHTTPFetcher']['source']) {
        $form['sync_user_feed']['url']['#value'] = '<div class="sub-url">'. l(check_plain($url), $url) .'</div>';
        $form['sync_user_feed']['resubscribe']['#value'] = t('Refresh subscription');
      }
    }
  }
}

/**
 * Submit handler for subscription button.
 */
function sync_user_subscribe_submit($form, &$form_state) {
  $uid = $form_state['values']['_account']->uid;
  if ($openid = sync_user_openid($uid)) {
    if ($url = sync_user_subscription_url($openid)) {
      sync_user_unsubscribe($uid);
      sync_user_subscribe($uid, $url);
    }
  }
}

/**
 * Settings form.
 */
function sync_user_form() {
  $form = array();
  $form['sync_user_host'] = array(
    '#type' => 'textfield',
    '#title' => t('Provider host URL'),
    '#description' => t('Host URL to synchronize users from. Point to the root of a trusted Drupal site with PuSH user module installed. URL must have a trailing slash.'),
    '#default_value' => sync_user_host(),
  );
  if (module_exists('openid_sso')) {
    $form['sync_user_host']['#disabled'] = TRUE;
    $form['sync_user_host']['#description'] .= ' '. l(t('To change this value, change the OpenID Provider on the OpenID Simple Sign-On page.'), 'admin/settings/openid-sso');
  }
  return system_settings_form($form);
}

/**
 * Construct a subscription URL.
 */
function sync_user_subscription_url($openid) {
  $url = sync_user_host();
  $url .= 'user/feed?openid='. urlencode($openid);
  return $url;
}

/**
 * Get the sync user host. If OpenID SSO module is enabled, uses its settings.
 */
function sync_user_host() {
  if (module_exists('openid_sso')) {
    $provider = variable_get('openid_sso_provider', array());
    return $provider['url'];
  }
  return variable_get('sync_user_host', 'http://example.com/');
}

/**
 * Retrieve the OpenID for a given user, assume only 1.
 *
 * @todo: resolve the one OpenID per user restriction.
 */
function sync_user_openid($uid) {
  return db_result(db_query("SELECT authname FROM {authmap} WHERE uid = %d AND module = 'openid'", $uid));
}

/**
 * Subscribe a user.
 */
function sync_user_subscribe($uid, $url) {

  if (valid_url($url)) {
    $source = feeds_source('user_updates', $uid);
    $source->addConfig(array(
      'KeyAuthHTTPFetcher' => array(
        'source' => $url,
      ),
    ));
    $source->save();
    // @todo: move this to FeedsSource class.
    feeds_scheduler()->add('user_updates', 'import', $uid);
    feeds_scheduler()->add('user_updates', 'expire');
  }
}

/**
 * Unsubscribe a user.
 */
function sync_user_unsubscribe($uid) {
  feeds_scheduler()->remove('user_updates', 'import', $uid);
  feeds_scheduler()->remove('user_updates', 'subscribe', $uid);
  feeds_source('user_updates', $uid)->delete();
}